### ISSUE TITLE
Would like to learn how did you come up with dioxus-web-component?

### ISSUE THREAD

**Issue by codeitlikemiley** [ilaborie/dioxus-web-component#52]
I am trying to learn how to use wasm-bindgen with dioxus, 

i know you come up with this library, 

so im sure you guys are familiar on how to do it...

that said , i would appreciate it if you can disclose to me some code snippet i can test

that lead you towards creating this crates

as i think this is good tool for fullstack dioxus

where you have axum as server , dioxus-ssr and , web-components all written in rust...

**Comment by ilaborie** [comment]
Web Component are only working in the Web, therefore does not work with SSR.
I don't think that this lib is the best way to learn Dioxus+wasm_bindgen.

Maybe this snippet will help you more:

```rust
use dioxus::prelude::*;
use dioxus::html::MountedEvent;
use dioxus_web::WebEventExt as _;
use wasm_bindgen::prelude::*;

// A Dioxus component that use PrismJs for highlighting code
#[component]
pub fn CodeBlock(language: String, code: String) -> Element {
    let highlight_code = |event: MountedEvent| {
        let elt = event.web_event(); // get the web-sys element
        Prism::highlight_element(elt);
    };

    rsx! {
        pre {
            code {
                class: "language-{language}",
                onmounted: highlight_code,
                "{code}"
            }
        }
    }
}

// Use of an external JS api
// (Prism should be added in the Dioxus.toml script)
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen]
    type Prism;

    #[wasm_bindgen(static_method_of = Prism, js_name = "highlightElement")]
    fn highlight_element(elt: &web_sys::Element);
}
```
